spring.application.name=autolibrary
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:school_library}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:A#1rnold233}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#I will update and remove this later
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false


server.port=${PORT:8080}

jwt.secret=aschoolautoarnoldanglibraSysForStudNyangoriBunyore23341
jwt.expiration=86400000


